### ISSUE TITLE
Error after Setting PowerBI Report Data Connections

### ISSUE THREAD

**Issue by MarianoKovo** [ctesta-oneillmsft/asa-vtd#10]
Hi Team, I've got the following error in the deployment script:
![image](https://user-images.githubusercontent.com/32372763/97220556-6b7a7a00-17aa-11eb-8f6b-3c6e2199b510.png)

The result was that the Power BI Workspace was not linked in the Synapse Studio.

**Comment by joelhulen** [comment]
@givenscj Do you have any suggestions for this issue?

**Comment by givenscj** [comment]
This is an issue with the PowerBI backend. I'm not sure when they will have it fixed (if ever).  We solved this previously by creating multiple reports/datasets from the same source file until one works.  Total hack, but eventually gets around it.  I'll have to think through how this could be automated to get around the error in the backend.
