### ISSUE TITLE
Error Instruction Power BI 

### ISSUE THREAD

**Issue by Kaijisse** [ctesta-oneillmsft/asa-vtd#18]
"From the hamburger menu select Workspaces to access the list of workspaces available to you. Select your workspace."
If the set up for the workspace is not working in the error of the setup script of powerbi, what workspace I should select here?
Should I create a new workspace?
Can we please clarify the steps around power bi when it's not set up through the power shell script?

**Comment by joelhulen** [comment]
@Kaijisse, the workspace will be the same name as your resource group you used for your demo resources. I'll update the instructions accordingly. Can you see a workspace names after the resource group?

**Comment by Kaijisse** [comment]
@joelhulen  no because there is no workspace for power bi deployed through the powershell script. I can manually create a workspace with the name of the resource group if that's what I need to do? But when going to power bi and login with my credentials there has been no workspace or whatsoever deployed due to the errors of the powershell script as soon as it gets to the power bi part. Also if you go to lab 1 Stage 3: Visualize, there are no artificats in the Develop Hub in Synapse Studio for Power BI deployed due to the errors of the powershell script.

**Comment by joelhulen** [comment]
@Kaijisse makes sense. I believe the workaround is to create the Power BI workspace before running the script. The workspace name needs to be the same as the resource group name since the script uses that value to create the Power BI workspace if it doesn't exist, or retrieve it if it does.

**Comment by Kaijisse** [comment]
@joelhulen can we specify that somewhere in the instructions? I've tested it as is and it didn't work. Do you suggest me running the script again but first create the workspace with the same name as the resource group? Since we mention as naming for resource group: synapse-in-a-day-demos, should I include the 'minuses' in the naming of the workspace (i.e. synapse-in-a..). If I need to run again the whole script it's going to take a while but I'll test it if you're sure that should work.

**Comment by joelhulen** [comment]
@Kaijisse Yes, I can specify that in the setup instructions before running the script. Yes, do include the 'minuses' in the name. It should exactly match the name of your resource group, whatever it is.

Perhaps you could try it with a new resource group/Power BI workspace name (`synapse-in-a-day-demos2`) and re-run the setup starting with deploying the Azure resources? That way you can let that run in the background while you continue testing with your existing deployed environment.

By the way, you should be able to successfully test all but the first lab without the Power BI configuration.

**Comment by Kaijisse** [comment]
@joelhulen perfect. I know, since I've been through the repo and not much changed, I was mainly focussing for set-up though. Thank you so much and I'll rerun all the setup steps but first creating a workspace with exact name of the resourcegroup.

**Comment by joelhulen** [comment]
Since @Kaijisse verified my proposed workaround works, I've updated the lab instructions accordingly to create the Power BI workspace first.
