### ISSUE TITLE
errorPBI

### ISSUE THREAD

**Issue by Kaijisse** [ctesta-oneillmsft/asa-vtd#19]
Hi. This is the only error I received through the error of the PBI. I tested local and on VM. 
Please let me know?
[errorpowerbiArtifacts.txt](https://github.com/ctesta-oneillmsft/asa-vtd/files/5850697/errorpowerbiArtifacts.txt)

**Comment by joelhulen** [comment]
@Kaijisse I think this is OK. I also encountered the same error the other day when I deployed my lab environment. The big test is to see if the datasets and reports were added to the associated Power BI workspace. If you complete the steps at the bottom of the setup guide, you should see that those artifacts exist. Please confirm.

**Comment by joelhulen** [comment]
I've added this as a message that can be safely ignored.
