### ISSUE TITLE
Task 5 Setup shows errors

### ISSUE THREAD

**Issue by ctesta-oneillmsft** [ctesta-oneillmsft/asa-vtd#2]
Hi

When running the setup script there are the following messages, but no indication on the instructions.

please can you advise @joelhulen or @givenscj 

Thanks

Chris
![Task5messages](https://user-images.githubusercontent.com/33545180/94158669-95bedc00-fe7a-11ea-8667-bafef2a57abf.png)

**Comment by joelhulen** [comment]
@ctesta-oneillmsft did you sign in to Azure from PowerShell before running the script?

**Comment by ctesta-oneillmsft** [comment]
That would help :-)

**Comment by ctesta-oneillmsft** [comment]
I will run through it again tomorrow

**Comment by ctesta-oneillmsft** [comment]
HI @joelhulen 

I did login this time and I am recieving similar errors.
 Can we jump on a call?
