### ISSUE TITLE
DeployArmTemplate Issue Spark Pool

### ISSUE THREAD

**Issue by Kaijisse** [ctesta-oneillmsft/asa-vtd#23]
error:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidSparkPoolConfigProperties","message":"Invalid content in SparkConfigProperties. Content should be space delimited key-value pairs."}]}

**Comment by joelhulen** [comment]
Yes, this error just started happening with all of our Synapse deployments that contain a requirements file definition. There appears to be a regression in both the format of the file contents and the ARM template itself. I believe I have a fix. I need to finish testing it first.

**Comment by joelhulen** [comment]
This issue is now fixed.

**Comment by bpons-mir** [comment]
@joelhulen how did you fix that?
