### ISSUE TITLE
 Lifetime validation failed. The token is expired.

### ISSUE THREAD

**Issue by ozanabuse** [ctesta-oneillmsft/asa-vtd#24]
I still get an issue that was marked as closed and solved (title "Expired Authentication Token Error").
I tried multiple times and it fails at "Creating pipeline Setup - Load SQL Pool (global)".

PS snippet:

Create pipeline to load the SQL pool
Creating pipeline Setup - Load SQL Pool (global)

id         : /subscriptions/0458e9d8-af13-486a-abfd-d86axxx/resourceGroups/synapseozanademo/providers/Microsoft.Sy
             napse/workspaces/asaworkspacesynapseozana/pipelines/Setup - Load SQL Pool (global)
name       : Setup - Load SQL Pool (global)
type       : Microsoft.Synapse/workspaces/pipelines
properties : @{activities=System.Object[]; parameters=; annotations=System.Object[];
             lastPublishTime=2021-03-18T16:17:25Z}
etag       : 7c00901c-0000-0c00-0000-60537d150000

Running pipeline Setup - Load SQL Pool (global)
Invoke-RestMethod : {"code":"ExpiredAuthenticationToken","message":"Token Authentication failed with
SecurityTokenExpiredException - IDX10223: Lifetime validation failed. The token is expired. ValidTo: '[PII is
hidden]', Current time: '[PII is hidden]'."}
At C:\labfiles\synapse-in-a-day-deployment\artifacts\environment-setup\solliance-synapse-automation\solliance-synapse-a
utomation.psm1:616 char:15
+ ...   $result = Invoke-RestMethod  -Uri $uri -Method GET -Headers @{ Auth ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Deleting pipeline Setup - Load SQL Pool (global)
Invoke-RestMethod : {"code":"ExpiredAuthenticationToken","message":"Token Authentication failed with
SecurityTokenExpiredException - IDX10223: Lifetime validation failed. The token is expired. ValidTo: '[PII is
hidden]', Current time: '[PII is hidden]'."}
At C:\labfiles\synapse-in-a-day-deployment\artifacts\environment-setup\solliance-synapse-automation\solliance-synapse-a
utomation.psm1:727 char:15
+ ...   $result = Invoke-RestMethod  -Uri $uri -Method DELETE -Headers @{ A ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Deleting dataset wwi02_sale_small_adls
@{code=BadRequest; message=Validation failed. This generally happens when the resource requested for deletion is
referred as a dependency in other resources.}
At C:\labfiles\synapse-in-a-day-deployment\artifacts\environment-setup\solliance-synapse-automation\solliance-synapse-a
utomation.psm1:695 char:13
+             throw $result.error
+             ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (@{code=BadReque...her resources.}:PSObject) [], RuntimeException
    + FullyQualifiedErrorId : @{code=BadRequest; message=Validation failed. This generally happens when the resource r
   equested for deletion is referred as a dependency in other resources.}

**Comment by joelhulen** [comment]
We were unable to recreate this issue after adding more refresh tokens. Can you please confirm which Azure region you are using when running the ARM template and scripts?
