### ISSUE TITLE
Task Failed exception error

### ISSUE THREAD

**Issue by Kaijisse** [ctesta-oneillmsft/asa-vtd#8]
Task Failed exception error:

@{code=CreateOrUpdateDataFactoryResourceOrchestrationException; message=DurableTask.Core.Exceptions.TaskFailedException : {"code":"BadRequest","message":"The document creation or update failed because of invalid reference
'wwi02_poc_customer_adls'.","target":"/subscriptions/xxx/resourceGroups/synapse-in-a-day-demos/providers/Microsoft.DataFactory/factories/asaworkspacekaito/pipelines/Setup - Load SQL
Pool","details":null,"error":null}

**Comment by joelhulen** [comment]
This appears to be related to #7. Please download the latest scripts and try again, carefully following each step. I just successfully completed the setup from a brand new VM inside a new Pay-as-you-go subscription.
