### ISSUE TITLE
Deleting Datasets Issue

### ISSUE THREAD

**Issue by Kaijisse** [ctesta-oneillmsft/asa-vtd#9]
Not sure why, but when I run the script it starts deleting the below datasets:
Deleting pipeline Setup - Load SQL Pool (global)
Deleting dataset wwi02_sale_small_adls
Deleting dataset wwi02_date_adls
Deleting dataset wwi02_date_asa
Deleting dataset wwi02_product_adls
Deleting dataset wwi02_sale_small_asa
Deleting dataset wwi02_product_asa

**Comment by joelhulen** [comment]
This is expected. These are temporary datasets used by the setup scripts, then deleted at the end.
